# Generated by Django 2.2.4 on 2019-08-11 22:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avaliacao_desc', models.TextField(max_length=1000)),
                ('avaliacao_pontuacao', models.IntegerField()),
                ('avaliacao_datahora', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(max_length=1000)),
                ('datahora', models.DateTimeField(auto_now_add=True)),
                ('avaliacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Avaliacao')),
                ('likes', models.ManyToManyField(blank=True, related_name='comentario_likes', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rua', models.CharField(max_length=100)),
                ('numero', models.IntegerField()),
                ('cep', models.CharField(max_length=10)),
                ('bairro', models.CharField(max_length=45)),
                ('cidade', models.CharField(max_length=20)),
                ('estado', models.CharField(max_length=2)),
                ('pais', models.CharField(max_length=45)),
                ('complemento', models.CharField(blank=True, max_length=45, null=True)),
                ('pontoreferencia', models.CharField(blank=True, max_length=45, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servico_desc', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Telefone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=15)),
                ('ramal', models.CharField(blank=True, max_length=4, null=True)),
                ('nome_contato', models.CharField(blank=True, max_length=45, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoFornecedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cnpj', models.CharField(max_length=20)),
                ('logo', models.ImageField(blank=True, default='fornecedores/default.jpg', null=True, upload_to='fornecedores/logos/', verbose_name='Logo')),
                ('avaliacoes', models.ManyToManyField(through='core.Avaliacao', to=settings.AUTH_USER_MODEL)),
                ('endereco', models.ManyToManyField(to='core.Endereco')),
                ('servicos', models.ManyToManyField(to='core.Servico')),
                ('telefones', models.ManyToManyField(to='core.Telefone')),
                ('tipo_empresa', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.TipoFornecedor')),
            ],
        ),
        migrations.CreateModel(
            name='Denuncia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Comentario')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria_title', models.CharField(max_length=45)),
                ('categoria_desc', models.TextField(max_length=400)),
                ('imagem', models.ImageField(blank=True, default='categorias/default.jpg', null=True, upload_to='categorias/imagens/', verbose_name='Imagem')),
                ('slug', models.SlugField(blank=True, max_length=60, verbose_name='slug')),
                ('servicos', models.ManyToManyField(to='core.Servico')),
            ],
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='fornecedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Fornecedor'),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='avaliacao_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
