# Generated by Django 2.2.4 on 2019-08-12 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190812_0321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fornecedor',
            name='tipo_empresa',
        ),
        migrations.DeleteModel(
            name='TipoFornecedor',
        ),
    ]
