# Generated by Django 2.2.4 on 2019-08-12 03:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190812_0325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fornecedor',
            name='telefones',
        ),
        migrations.RemoveField(
            model_name='telefone',
            name='ramal',
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='cep',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='telefone',
            name='fornecedor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Fornecedor'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='fornecedor',
            name='endereco',
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='endereco',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Endereco',
        ),
    ]
